import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Everything TypeORM's generator cannot express.
 *
 *   A. serial → identity, for four columns the generator got wrong
 *   B. CHECK constraints — the integrity guards from DATA-MODEL §10
 *   C. Functional and partial unique indexes
 *   D. Trigram indexes for search
 *
 * Rollup triggers, the ledger balance guard, append-only guards and the drift
 * views live in the Rollups migration.
 */
export class Constraints1785517150000 implements MigrationInterface {
  name = "Constraints1785517150000";

  public async up(q: QueryRunner): Promise<void> {
    /* ───────────────────────────────────────────────────────────────────
       A. serial → identity
       The generator emitted BIGSERIAL for these four while every other
       document number came out as an identity column. Left alone, the next
       `db:generate` reports a phantom diff forever. DATA-MODEL D-2 specifies
       identity, BY DEFAULT so a restore or import can still supply a value.
       ─────────────────────────────────────────────────────────────────── */
    for (const [table, column] of [
      ["party_orders", "party_no"],
      ["payments", "payment_no"],
      ["audit_logs", "id"],
      ["document_revisions", "id"],
    ] as const) {
      await q.query(`ALTER TABLE "${table}" ALTER COLUMN "${column}" DROP DEFAULT`);
      await q.query(
        `ALTER TABLE "${table}" ALTER COLUMN "${column}" ADD GENERATED BY DEFAULT AS IDENTITY`,
      );
      // Carry the old sequence's position across, or the first insert collides.
      await q.query(`
        SELECT setval(
          pg_get_serial_sequence('${table}', '${column}'),
          COALESCE((SELECT MAX("${column}") FROM "${table}"), 0) + 1,
          false
        )
      `);
      await q.query(`DROP SEQUENCE IF EXISTS "${table}_${column}_seq"`);
    }

    /* ───────────────────────────────────────────────────────────────────
       B. CHECK constraints — DATA-MODEL §10
       ─────────────────────────────────────────────────────────────────── */

    // Walk-ins are always fully paid in cash. Encoding it as a constraint
    // rather than a nullable status makes the invalid state unrepresentable.
    // Relaxing it for UPI later is a one-line migration. §5.18
    await q.query(`
      ALTER TABLE "direct_sales"
        ADD CONSTRAINT "chk_direct_sales_cash_only" CHECK ("mode" = 'CASH'),
        ADD CONSTRAINT "chk_direct_sales_amount_positive" CHECK ("amount" > 0)
    `);

    // Exclusive arc: exactly one context FK, and it must agree with
    // context_type. A bare payable_type/payable_id pair would allow a payment
    // pointing at a deleted order. §5.8
    await q.query(`
      ALTER TABLE "payments"
        ADD CONSTRAINT "chk_payments_arc" CHECK (
          num_nonnulls("order_id", "coin_issue_id", "party_order_id") = 1
          AND (
            ("context_type" = 'ORDER'       AND "order_id"       IS NOT NULL) OR
            ("context_type" = 'COIN_ISSUE'  AND "coin_issue_id"  IS NOT NULL) OR
            ("context_type" = 'PARTY_ORDER' AND "party_order_id" IS NOT NULL)
          )
        ),
        -- The sign lives in 'direction', never in the number.
        ADD CONSTRAINT "chk_payments_amount_positive" CHECK ("amount" > 0),
        -- Coin fields are required exactly when mode = 'COIN', and the amount
        -- must equal the coin count times the snapshotted per-coin value.
        ADD CONSTRAINT "chk_payments_coin_fields" CHECK (
          ("mode" = 'COIN' AND "coin_type_id" IS NOT NULL
            AND "coin_count" IS NOT NULL AND "coin_count" > 0
            AND "coin_unit_value" IS NOT NULL
            AND "amount" = round("coin_count"::numeric * "coin_unit_value", 2))
          OR
          ("mode" <> 'COIN' AND "coin_type_id" IS NULL
            AND "coin_count" IS NULL AND "coin_unit_value" IS NULL)
        )
    `);

    // The ledger is the auditable spine — guard it hard. §5.14
    await q.query(`
      ALTER TABLE "coin_ledger_entries"
        ADD CONSTRAINT "chk_ledger_arc" CHECK (
          num_nonnulls("coin_issue_item_id", "coin_issue_return_event_id",
                       "payment_id", "coin_adjustment_id") = 1
        ),
        ADD CONSTRAINT "chk_ledger_source_matches" CHECK (
          ("source_type" = 'COIN_ISSUE_ITEM'         AND "coin_issue_item_id"         IS NOT NULL) OR
          ("source_type" = 'COIN_ISSUE_RETURN_EVENT' AND "coin_issue_return_event_id" IS NOT NULL) OR
          ("source_type" = 'PAYMENT'                 AND "payment_id"                 IS NOT NULL) OR
          ("source_type" = 'COIN_ADJUSTMENT'         AND "coin_adjustment_id"         IS NOT NULL)
        ),
        ADD CONSTRAINT "chk_ledger_delta_nonzero" CHECK ("coins_delta" <> 0),
        -- Stock can never go negative. The trigger checks this too, under a
        -- row lock; the constraint is the backstop. §10.2
        ADD CONSTRAINT "chk_ledger_balance_non_negative" CHECK ("balance_after_coins" >= 0),
        -- Only these two movement types remove coins from company stock.
        ADD CONSTRAINT "chk_ledger_sign" CHECK (
          ("movement_type" IN ('ISSUE', 'ADJUSTMENT_OUT')) = ("coins_delta" < 0)
        )
    `);

    await q.query(`
      ALTER TABLE "coin_types"
        ADD CONSTRAINT "chk_coin_types_packet_size" CHECK ("coins_per_packet" > 0),
        ADD CONSTRAINT "chk_coin_types_packet_amount" CHECK ("packet_amount" >= 0),
        ADD CONSTRAINT "chk_coin_types_balance_non_negative" CHECK ("balance_coins" >= 0)
    `);

    await q.query(`
      ALTER TABLE "coin_issue_items"
        ADD CONSTRAINT "chk_cii_packets_positive" CHECK ("packets" > 0),
        -- Over-return guard: you cannot hand back more than went out. §10.1
        ADD CONSTRAINT "chk_cii_returned_within_issued" CHECK (
          "coins_returned" >= 0
          AND "coins_returned" <= "packets" * "coins_per_packet_snapshot"
        )
    `);

    await q.query(`
      ALTER TABLE "coin_adjustments"
        ADD CONSTRAINT "chk_coin_adjustments_coins_positive" CHECK ("coins" > 0),
        -- A stock adjustment with no explanation is how theft hides. §5.13
        ADD CONSTRAINT "chk_coin_adjustments_note_present"
          CHECK (length(btrim("note")) > 0)
    `);

    await q.query(`
      ALTER TABLE "party_order_items"
        ADD CONSTRAINT "chk_poi_quantity_positive" CHECK ("quantity" > 0),
        ADD CONSTRAINT "chk_poi_unit_price_non_negative" CHECK ("unit_price" >= 0),
        ADD CONSTRAINT "chk_poi_delivered_non_negative"
          CHECK ("delivered_quantity" IS NULL OR "delivered_quantity" >= 0)
    `);

    await q.query(`
      ALTER TABLE "products"
        ADD CONSTRAINT "chk_products_litres_positive" CHECK ("litres" > 0),
        ADD CONSTRAINT "chk_products_base_price_non_negative" CHECK ("base_price" >= 0),
        ADD CONSTRAINT "chk_products_title_present" CHECK (length(btrim("title")) > 0)
    `);

    await q.query(`
      ALTER TABLE "staff"
        ADD CONSTRAINT "chk_staff_name_present" CHECK (length(btrim("name")) > 0),
        -- Digits, spaces, + and - only. Deliberately loose: this is the ONLY
        -- field in the app with a character-class restriction, because a phone
        -- number genuinely is numeric. Names and addresses never get one — it
        -- would silently block Gujarati. See .claude/I18N.md §3.1
        ADD CONSTRAINT "chk_staff_phone_format" CHECK ("phone" ~ '^[0-9+][0-9 +-]{6,19}$')
    `);

    await q.query(`
      ALTER TABLE "expenses"
        ADD CONSTRAINT "chk_expenses_amount_positive" CHECK ("amount" > 0)
    `);

    /* ───────────────────────────────────────────────────────────────────
       C. Functional and partial unique indexes
       No TypeORM decorator can express lower(name) or a partial predicate.
       ─────────────────────────────────────────────────────────────────── */

    // Case-insensitive uniqueness among live rows: "Blue Token" and
    // "blue token" must not coexist, but a deleted name frees up. §5.9
    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_coin_types_name_ci"
        ON "coin_types" (lower("name")) WHERE "deleted_at" IS NULL
    `);

    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_staff_phone_live"
        ON "staff" ("phone") WHERE "deleted_at" IS NULL
    `);

    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_expense_categories_name_ci"
        ON "expense_categories" (lower("name")) WHERE "deleted_at" IS NULL
    `);

    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_products_title_ci"
        ON "products" (lower("title")) WHERE "deleted_at" IS NULL
    `);

    // One payment per client request — an idempotency key that kills
    // double-submit on a flaky mobile connection. §5.8
    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_payments_client_request"
        ON "payments" ("client_request_id") WHERE "client_request_id" IS NOT NULL
    `);

    // Per-coin-type monotonic sequence, assigned under a row lock. §5.14
    await q.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_ledger_seq"
        ON "coin_ledger_entries" ("coin_type_id", "entry_seq" DESC)
    `);

    /* ───────────────────────────────────────────────────────────────────
       D. Trigram indexes for search
       One GIN index per generated search_blob serves the whole free-text box,
       instead of three ILIKE OR-branches each needing its own index. §5.2
       ─────────────────────────────────────────────────────────────────── */
    for (const table of [
      "staff",
      "products",
      "party_orders",
      "direct_sales",
      "expenses",
    ]) {
      await q.query(`
        CREATE INDEX IF NOT EXISTS "idx_${table}_search_trgm"
          ON "${table}" USING gin ("search_blob" gin_trgm_ops)
      `);
    }

    // Document codes are searched directly (ORD-000123), and are generated
    // columns so they cannot be folded into search_blob.
    for (const table of [
      "delivery_orders",
      "coin_issues",
      "party_orders",
      "direct_sales",
      "expenses",
      "products",
      "staff",
    ]) {
      await q.query(`
        CREATE INDEX IF NOT EXISTS "idx_${table}_code_trgm"
          ON "${table}" USING gin ("code" gin_trgm_ops)
      `);
    }

    /* ───────────────────────────────────────────────────────────────────
       E. The two headline filters.
       Tiny partial indexes, always hot: "show me everything with money
       pending" and "show me everything with jars out" are the two questions
       the owner asks most. §11
       ─────────────────────────────────────────────────────────────────── */
    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_orders_payment_pending"
        ON "delivery_orders" ("order_date" DESC, "staff_id")
        WHERE "deleted_at" IS NULL AND "outstanding_amount" > 0
    `);

    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_orders_return_pending"
        ON "delivery_orders" ("order_date" DESC, "staff_id")
        WHERE "deleted_at" IS NULL AND "qty_pending" > 0
    `);

    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_coin_issues_pending"
        ON "coin_issues" ("issue_date" DESC)
        WHERE "deleted_at" IS NULL AND "outstanding_amount" <> 0
    `);

    await q.query(`
      CREATE INDEX IF NOT EXISTS "idx_party_orders_pending"
        ON "party_orders" ("first_service_date" DESC)
        WHERE "deleted_at" IS NULL AND "outstanding_amount" > 0
    `);
  }

  public async down(q: QueryRunner): Promise<void> {
    const indexes = [
      "idx_party_orders_pending",
      "idx_coin_issues_pending",
      "idx_orders_return_pending",
      "idx_orders_payment_pending",
      "uq_ledger_seq",
      "uq_payments_client_request",
      "uq_products_title_ci",
      "uq_expense_categories_name_ci",
      "uq_staff_phone_live",
      "uq_coin_types_name_ci",
    ];
    for (const t of ["staff", "products", "party_orders", "direct_sales", "expenses"]) {
      indexes.push(`idx_${t}_search_trgm`);
    }
    for (const t of [
      "delivery_orders", "coin_issues", "party_orders",
      "direct_sales", "expenses", "products", "staff",
    ]) {
      indexes.push(`idx_${t}_code_trgm`);
    }
    for (const i of indexes) {
      await q.query(`DROP INDEX IF EXISTS "${i}"`);
    }

    const constraints: [string, string[]][] = [
      ["expenses", ["chk_expenses_amount_positive"]],
      ["staff", ["chk_staff_name_present", "chk_staff_phone_format"]],
      ["products", [
        "chk_products_litres_positive",
        "chk_products_base_price_non_negative",
        "chk_products_title_present",
      ]],
      ["party_order_items", [
        "chk_poi_quantity_positive",
        "chk_poi_unit_price_non_negative",
        "chk_poi_delivered_non_negative",
      ]],
      ["coin_adjustments", [
        "chk_coin_adjustments_coins_positive",
        "chk_coin_adjustments_note_present",
      ]],
      ["coin_issue_items", [
        "chk_cii_packets_positive",
        "chk_cii_returned_within_issued",
      ]],
      ["coin_types", [
        "chk_coin_types_packet_size",
        "chk_coin_types_packet_amount",
        "chk_coin_types_balance_non_negative",
      ]],
      ["coin_ledger_entries", [
        "chk_ledger_arc",
        "chk_ledger_source_matches",
        "chk_ledger_delta_nonzero",
        "chk_ledger_balance_non_negative",
        "chk_ledger_sign",
      ]],
      ["payments", [
        "chk_payments_arc",
        "chk_payments_amount_positive",
        "chk_payments_coin_fields",
      ]],
      ["direct_sales", [
        "chk_direct_sales_cash_only",
        "chk_direct_sales_amount_positive",
      ]],
    ];
    for (const [table, names] of constraints) {
      for (const n of names) {
        await q.query(`ALTER TABLE "${table}" DROP CONSTRAINT IF EXISTS "${n}"`);
      }
    }

    // Identity columns are left as identity — reverting them to serial would
    // be strictly worse than the state this migration created.
  }
}
