import type { DirectSale } from "@/lib/db/entities";
import type { ListResult } from "@/lib/table/types";

/**
 * Plain shapes crossing the server → client boundary.
 *
 * TypeORM entities are CLASS INSTANCES; React's serialiser rejects any object
 * whose prototype isn't Object.prototype ("Only plain objects can be passed to
 * Client Components"). Mapping once here also means a column added to the
 * entity never leaks to the browser by accident — it simply isn't part of the
 * shape. See .claude/ARCHITECTURE.md §4.1 rule 8
 *
 * **Every money figure on these shapes came out of SQL.** Nothing below is a
 * `reduce` over rupees in TypeScript — see ARCHITECTURE §9.1 and the aggregate
 * methods on `DirectSaleRepository`.
 */

export interface DirectSaleDto {
  id: string;
  /** `DWS-000329` — generated by the database from sale_no. */
  code: string;
  /** `'YYYY-MM-DD'`, never a Date. The business day the cash belongs to. */
  saleDate: string;
  /** ISO string. The INSTANT — walk-ins cluster by hour, which is useful. */
  soldAt: string;
  /** One field, any script. There is no English/Gujarati pair (D-10). */
  customerName: string;
  phone: string | null;
  address: string | null;
  amount: number;
  litres: number | null;
  productId: string | null;
  /** Denormalised for display; the row is useless without the product's name. */
  productTitle: string | null;
  /** Always `CASH` — a CHECK constraint makes anything else unrepresentable. */
  mode: string;
  isVoided: boolean;
  voidReason: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface DirectSaleListItemDto extends DirectSaleDto {
  /**
   * How many times this customer has been in, matched on phone when there is
   * one and on an exact name otherwise. 2+ earns the `Repeat` marker. Counted
   * in SQL, one grouped query for the whole page.
   */
  visitCount: number;
  /** Same-day entries can be corrected; older ones can only be voided. */
  canEdit: boolean;
}

/**
 * One day-group band — the cash-drawer tally the owner reconciles at close.
 *
 * `total` and both counts are SQL aggregates over `direct_sales`, filtered so
 * voided rows are excluded from the money and counted separately. The band
 * reads `12 sales · 1 voided`. See design/MODULES/06-direct-sales.md §3.3
 */
export interface DirectSaleDayGroupDto {
  /** `'YYYY-MM-DD'` — the key the client groups rows by. */
  date: string;
  count: number;
  voidedCount: number;
  total: number;
}

/** The four KPI cards above the list. */
export interface DirectSaleStatsDto {
  /** `'YYYY-MM-DD'` in IST, so the client never recomputes "today". */
  today: string;
  yesterday: string;
  todayCount: number;
  todayTotal: number;
  yesterdayCount: number;
  yesterdayTotal: number;
  monthCount: number;
  monthTotal: number;
  /** `AVG(amount)` over today's live sales — computed by PostgreSQL. */
  averageToday: number;
  /** First day of the current month, for the `248 sales · August` line. */
  monthFrom: string;
}

/** What `GET /api/direct-sales` returns: the page, the bands and the KPIs. */
export interface DirectSaleListDto {
  result: ListResult<DirectSaleListItemDto>;
  stats: DirectSaleStatsDto;
  /**
   * One entry per distinct `saleDate` on THIS page. Page-local by design: a
   * day split across two pages gets a band on each. §3.3
   */
  dayGroups: DirectSaleDayGroupDto[];
}

/** A row in the detail page's "This customer's other walk-ins" table. */
export interface DirectSaleSiblingDto {
  id: string;
  code: string;
  saleDate: string;
  litres: number | null;
  amount: number;
  isVoided: boolean;
}

export interface DirectSaleDetailDto extends DirectSaleListItemDto {
  /** `by Admin` under the RECORDED figure. */
  recordedByName: string | null;
  voidedByName: string | null;
  voidedAt: string | null;
  /**
   * How the earlier visits were found, so the card can say
   * `matched on 9825014477` or `matched on the name "Paresh Bhai"` rather than
   * leaving the owner to assume a first-timer. `null` = nothing to match on.
   */
  matchedOn: "phone" | "name" | null;
  siblings: DirectSaleSiblingDto[];
  /** Live sales only, excluding this one. A SQL SUM. */
  siblingTotal: number;
  siblingCount: number;
  /**
   * `₹3.00 per litre`, computed once here. A division for display, not an
   * accumulation — no rupees are added up in TypeScript. `null` when no litre
   * figure was recorded.
   */
  perLitre: number | null;
  /** This sale's day total, for the void dialog's impact line. SQL SUM. */
  dayTotal: number;
  /** The same SUM with this row excluded — so the dialog never subtracts. */
  dayTotalAfterVoid: number;
}

/**
 * One option in the entry row's customer autocomplete.
 *
 * There is no customer entity; this is built from past walk-ins (§7), which is
 * exactly the data that would seed a customer master if one were ever needed.
 */
export interface DirectSaleCustomerSuggestionDto {
  name: string;
  phone: string | null;
  address: string | null;
  /** `'YYYY-MM-DD'` — `last 12 Aug` on the option's second line. */
  lastSaleDate: string;
  /** `₹120.00 avg` — `AVG(amount)`, computed by PostgreSQL. */
  averageAmount: number;
  visitCount: number;
}

/** Shape of `GET /api/direct-sales/options` — matches ComboboxOption. */
export interface DirectSaleOptionDto {
  id: string;
  label: string;
  hint?: string;
}

/* ═══════════════════════════════════════════════════════════════════════
   Mappers
   ═══════════════════════════════════════════════════════════════════════ */

export function toDirectSaleDto(sale: DirectSale): DirectSaleDto {
  return {
    id: sale.id,
    code: sale.code,
    saleDate: sale.saleDate,
    soldAt: sale.soldAt.toISOString(),
    customerName: sale.customerName,
    phone: sale.phone,
    address: sale.address,
    amount: sale.amount,
    litres: sale.litres,
    productId: sale.productId,
    // Present only when the caller joined it; a missing relation must read as
    // "no product recorded", not crash.
    productTitle: sale.product?.title ?? null,
    mode: sale.mode,
    isVoided: sale.isVoided,
    voidReason: sale.voidReason,
    note: sale.note,
    createdAt: sale.createdAt.toISOString(),
    updatedAt: sale.updatedAt.toISOString(),
  };
}

export function toDirectSaleListItemDto(
  sale: DirectSale,
  extras: { visitCount: number; canEdit: boolean },
): DirectSaleListItemDto {
  return { ...toDirectSaleDto(sale), ...extras };
}

export function toDirectSaleSiblingDto(sale: DirectSale): DirectSaleSiblingDto {
  return {
    id: sale.id,
    code: sale.code,
    saleDate: sale.saleDate,
    litres: sale.litres,
    amount: sale.amount,
    isVoided: sale.isVoided,
  };
}
