import type { AuditLog, Staff } from "@/lib/db/entities";
import type { ListResult } from "@/lib/table/types";

/**
 * Plain shapes crossing the server → client boundary.
 *
 * TypeORM entities are CLASS INSTANCES; React's serialiser rejects any object
 * whose prototype isn't Object.prototype ("Only plain objects can be passed to
 * Client Components"). Mapping once here also means a column added to the
 * entity never leaks to the browser by accident — it simply isn't part of the
 * shape. See .claude/ARCHITECTURE.md §4.1 rule 8
 */

/* ═══════════════════════════════════════════════════════════════════════
   Outstanding figures

   These aggregate delivery_orders, coin_issues and their returns — tables
   that belong to other modules and hold no data yet. They are carried on the
   DTO from day one so the list, the badges and the deactivation guard are
   written against their final shape, and wave 3 changes only where the
   numbers come from.
   ═══════════════════════════════════════════════════════════════════════ */

export interface StaffOutstanding {
  /** Cash still owed against delivery orders. */
  cashOutstanding: number;
  /** Jars issued and not yet returned. A count, not money. */
  jarsOut: number;
  /** Value of coins issued and not yet returned or paid for. */
  coinDues: number;
  /**
   * `cashOutstanding + coinDues`, **computed in SQL**.
   *
   * Carried as its own field rather than added up in a component: adding
   * monetary values in TypeScript is a code-review failure in this codebase,
   * and the badge needs the combined figure. See ARCHITECTURE §9.1
   */
  moneyOutstanding: number;
}

export interface StaffDto {
  id: string;
  /** `STF-000004` — generated by the database from staff_no. */
  code: string;
  name: string;
  phone: string;
  altPhone: string | null;
  address: string | null;
  note: string | null;
  /** `'YYYY-MM-DD'`, never a Date. See ARCHITECTURE §9.2 */
  joinedOn: string | null;
  isActive: boolean;
  /** ISO strings — flat DTOs serialise predictably. */
  createdAt: string;
  updatedAt: string;
}

export interface StaffListItemDto extends StaffDto, StaffOutstanding {}

export interface StaffActivityEntryDto {
  id: string;
  action: string;
  changedFields: string[];
  actorName: string | null;
  at: string;
}

export interface StaffDetailDto extends StaffListItemDto {
  /** Jars ever issued to this person, so "18 of 402" can be shown. */
  jarsTotal: number;
  lifetimeRevenue: number;
  /** Context lines under each summary figure, and the blocked-dialog counts. */
  openOrderCount: number;
  openIssueCount: number;
  jarsOutOrderCount: number;
  /** Tab counts — shown in the label so nothing hides behind a tab. */
  deliveryOrderCount: number;
  coinIssueCount: number;
  paymentCount: number;
  createdByName: string | null;
  updatedByName: string | null;
  activity: StaffActivityEntryDto[];
}

/** The four KPI cards above the list. */
export interface StaffStatsDto {
  totalStaff: number;
  activeStaff: number;
  inactiveStaff: number;
  cashOutstanding: number;
  jarsOut: number;
  /** "across 6 people" / "with 4 people". */
  staffWithBalance: number;
  staffWithJars: number;
}

/** What `GET /api/staff` returns: the page of rows plus the KPI strip. */
export interface StaffListDto {
  result: ListResult<StaffListItemDto>;
  stats: StaffStatsDto;
}

/**
 * One itemised reason a staff member cannot be deactivated.
 *
 * The dialog lists these verbatim, so a refusal always says exactly what is
 * open rather than "cannot deactivate". See design/MODULES/01-staff.md §7.3
 */
export interface StaffBlockerDto {
  kind: "cash" | "jars" | "coins";
  /** Money for `cash` and `coins`; a jar count for `jars`. */
  amount: number;
  /** How many orders or issues are behind the figure. */
  count: number;
}

/** Shape of `GET /api/staff/options` — matches the shared ComboboxOption. */
export interface StaffOptionDto {
  id: string;
  label: string;
  hint?: string;
}

/* ═══════════════════════════════════════════════════════════════════════
   Mappers
   ═══════════════════════════════════════════════════════════════════════ */

export function toStaffDto(staff: Staff): StaffDto {
  return {
    id: staff.id,
    code: staff.code,
    name: staff.name,
    phone: staff.phone,
    altPhone: staff.altPhone,
    address: staff.address,
    note: staff.note,
    joinedOn: staff.joinedOn,
    isActive: staff.isActive,
    createdAt: staff.createdAt.toISOString(),
    updatedAt: staff.updatedAt.toISOString(),
  };
}

export function toStaffListItemDto(
  staff: Staff,
  outstanding: StaffOutstanding,
): StaffListItemDto {
  return { ...toStaffDto(staff), ...outstanding };
}

export function toStaffActivityEntryDto(log: AuditLog): StaffActivityEntryDto {
  return {
    id: String(log.id),
    action: log.action,
    changedFields: log.changedFields ?? [],
    actorName: log.actorName,
    at: log.createdAt.toISOString(),
  };
}
